@startuml TestUseCase

left to right direction

actor :Tester: as Tester
'Why up? I have no fucking idea
Tester -u-> (Test Room Merge with Actors)
Tester -u-> (Test Student Moves to Room with Professor)
Tester -u-> (Test Item Pickright)
Tester -u-> (Test Professor Moves into Wet Room)
Tester -u-> (Test Student Merges into gassed Room)
Tester -u-> (Test Professor Moves into Room with Professor)
Tester -u-> (Test Student Uses Sponge)
Tester -u-> (Test Gas Effect Expire)
Tester -u-> (Test Room Split with Students)
Tester -u-> (Test Beer Effect Expires)
Tester -u-> (Test Student Moves into Room with Student)
Tester -u-> (Test Merge Rooms with Different Effects)
Tester --> (Test Professor Moves to Room with Student)
Tester --> (Test Student Moves into Room with Professor with TVSZ)
Tester --> (Test Student Moves into Wet Room)
Tester --> (Test Student Pairs Transistor)

Tester --> (Test Student Drops Transistor)
Tester --> (Test Student Teleports with Transistor)
Tester --> (Test Room Disappear)

Tester --> (Test Cocktail Use)
Tester --> (Test Student Gases Room without Mask)
Tester --> (Test Room Split with Students and Effects)
Tester --> (Test Beer Use)
Tester --> (Test Student Moves into Room with Professor Undefended)


@enduml