@startuml AddRoomEffect
header Actor Attack
hide footbox
autoactivate on

actor P as "Actor"
participant S as "state : ActionState"
participant R as "room : Room"
participant A as "actor : Actor"

P -> S++ : attack(actor)
S -> R++ : attack(actor)
loop foreach actor in room.actors
    R -> A ++: attacked()
    ref over A : Defense Strategy
    return
end
return
return

@enduml