@startuml ActorUseItem
header Actor Use Item

hide footbox
autoactivate on

actor A as "Controller"
participant B as "actor : Actor"
participant D as "item : Item"
participant C as "state : ActionState"

A -> B : use(item)
B -> C : use(item)
C -> D : use(actor)
ref over D : Delete Item

return
return
return
@enduml


