@startuml SetupBeerEffectTicks
header Setup Beer Effect Ticks
hide footbox

participant main as "Main"
activate main

create student as "student : Student"
main --> student : <<create>>
create studentAction as "studentAction : StudentActions"
student --> studentAction : <<create>>
create inventory as "studentInventory : Inventory"
student --> inventory : <<create>>
create defense as "studentDefense : DefaultDefense"
student --> defense --: <<create>>

create beerDefense as "beerDefense : BeerDefense"
main --> beerDefense : <<create>>

main --> student ++ : setDefenseStrategy(beerDefense)
return

@enduml