@startuml ProfessorStepsIntoWetRoom
skinparam headerFontSize 40
skinparam HeaderFontColor #000000
skinparam HeaderFontStyle bold
header Setup professor steps into wet room
hide footbox

participant main as "Main"
activate main

create room1 as "room1 : Room"
main --> room1 ++: <<create>>
create r1inv as "room1inventory : Inventory"
room1 --> r1inv --: <<create>>

create room2 as "room2 : Room"
main --> room2 ++: <<create>>
create r2inv as "room2inventory : Inventory"
room2 --> r2inv --: <<create>>

create door as "door : Door"
main --> door : <<create>>

create professor as "professor : Professor"
main --> professor ++: <<create>>
create action as "professorAction : ProfessorActions"
professor --> action : <<create>>
create profInventory as "professorInventory : Inventory"
professor --> profInventory : <<create>>
create profDefense as "professorDefense : DefaultDefense"
professor --> profDefense --: <<create>>
create wetEffect as "wetEffect : WetEffect"
main --> wetEffect : <<create>>

main -> room2 ++: addEffect (wetEffect)
return

main -> professor ++ : teleport(room1, false)
    professor -> room1++: enter(professor, false)
    return true
return true

@enduml