@startuml RoomSplitWithEffects
header Setup Room with Two Students, without any effects
hide footbox

participant M as "Main"
create R1 as "oRoom : Room"
M --> R1 :  <<create>>
create S1 as "student1 : Student"
M --> S1 ++: <<create>>
create S1S as "student1State : StudentActions"
S1 --> S1S : <<create>>
create S1I as "student1Inventory : Inventory"
S1 --> S1I : <<create>>
create S1D as "student1Defense : DefaultDefense"
S1 --> S1D --: <<create>>
create S2 as "student2 : Student"
M --> S2 ++: <<create>>
create S2S as "student2State : StudentActions"
S2 --> S2S : <<create>>
create S2I as "student2Inventory : Inventory"
S2 --> S2I : <<create>>
create S2D as "student2Defense : DefaultDefense"
S2 --> S2D --: <<create>>

M --> S1 ++ : teleport(oRoom, false)
return true
M --> S2 ++ : teleport(oRoom, false)
return true
@enduml

