@startuml RoomSplitWithEffects
header Setup Room with Two Students, Wet and Gas effects
hide footbox

participant M as "Main"
create R1 as "oRoom : Room"
M --> R1 :  <<create>>
activate R1
create R1I as "oRoomInventory : Inventory"
R1 --> R1I --: <<create>>

create S1 as "student1 : Student"
M --> S1 ++: <<create>>
create S1S as "student1State : StudentActions"
S1 --> S1S : <<create>>
create S1I as "student1Inventory : Inventory"
S1 --> S1I : <<create>>
create S1D as "student1Defense : DefaultDefense"
S1 --> S1D --: <<create>>
create S2 as "student2 : Student"
M --> S2 ++: <<create>>
create S2S as "student2State : StudentActions"
S2 --> S2S : <<create>>
create S2I as "student2Inventory : Inventory"
S2 --> S2I : <<create>>
create S2D as "student2Defense : DefaultDefense"
S2 --> S2D --: <<create>>
create W as "wetEffect : WetEffect"
M --> W : <<create>>
M -> R1 ++: addEffect(wetEffect)
R1 --> M --
create G as "gasEffect : GasEffect"
M --> G : <<create>>
M -> R1 ++: addEffect(gasEffect)
return

M -> S1 ++ : teleport(oRoom, false)
S1 -> R1 ++ : enter(student1, false)
return true
return true

M -> S2 ++ : teleport(oRoom, false)
S2 -> R1 ++ : enter(student2, false)
return success
return success

note over S2 : Undefined test behaviour if student2 is not in oRoom (success == false)
@enduml

