@startuml FullRoom
header Setup Neighbouring Rooms, with a student in one of them, and a a Wet Effect in the other
hide footbox

participant M as "Main"
activate M
create R1 as "room1 : Room"
M --> R1 :  <<create>>
activate R1
create R1I as "room1Inventory : Inventory"
R1 --> R1I --: <<create>>

create R2 as "room2 : Room"
M --> R2 :  <<create>>
activate R2
create R2I as "roomInventory : Inventory"
R2 --> R2I --: <<create>>


create S1 as "student1 : Student"
M --> S1 ++: <<create>>
create S1S as "student1State : StudentActions"
S1 --> S1S : <<create>>
create S1I as "student1Inventory : Inventory"
S1 --> S1I : <<create>>
create S1D as "student1Defense : DefaultDefense"
S1 --> S1D --: <<create>>

create W as "wetEffect : WetEffect"
M --> W : <<create>>
M -> R2 ++ : addEffect(wetEffect)
return

M -> S1 ++ : teleport(room1, false)
S1 -> R1 ++ : enter(student1, false)
return true
return true
@enduml

