@startuml FullRoom
header Setup a Room with a Student, who has a Camembert
hide footbox

participant M as "Main"
create R1 as "room1 : Room"
M --> R1 :  <<create>>
M --> R1 ++: addDoor(door)
return
create S1 as "student1 : Student"
M --> S1 ++: <<create>>
create S1S as "student1State : StudentActions"
S1 --> S1S : <<create>>
create S1I as "student1Inventory : Inventory"
S1 --> S1I : <<create>>
create S1D as "student1Defense : DefaultDefense"
S1 --> S1D --: <<create>>
create C as "camembert : Camembert"
M --> C : <<create>>
M --> S1 ++ : pickup(camembert)
S1 --> S1S ++ : pickup(camembert)
S1S --> S1I ++ : addItem(camembert)
S1I --> C ++ : onPickup(student1)
return
return true
return true
return true

@enduml

