@startuml SetupStudentUsesCoctail
header Setup Student Uses Coctail
hide footbox

participant main as "Main"
activate main

create room as "room : Room"
main --> room ++: <<create>>
create roomInventory as "roomInventory : Inventory"
room --> roomInventory --: <<create>>

create student as "student1 : Student"
main --> student ++: <<create>>
create studentAction as "student1Action : StudentActions"
student --> studentAction : <<create>>
create inventory as "student1Inventory : Inventory"
student --> inventory : <<create>>
create defense as "student1Defense : DefaultDefense"
student --> defense --: <<create>>

create student2 as "student2 : Student"
main --> student2 ++: <<create>>
create studentAction2 as "student2Action : StudentActions"
student2 --> studentAction2 : <<create>>
create inventory2 as "student2Inventory : Inventory"
student2 --> inventory2 : <<create>>
create defense2 as "student2Defense : DefaultDefense"
student2 --> defense2 --: <<create>>

main --> student ++: teleport(room, false)
return true

main --> student2 ++: teleport(room, false)
return true

/' todo 
itt baj lehet ha Simon B. úgy gondolja, hogy a szoba mérete state value
mert ebben az esetben ez nem egy garantált tp és a teszt értelmetlen
'/

create coctail as "coctail : Coctail"
main --> coctail : <<create>>

main --> student ++: getInventory()
return inventory

main --> inventory ++: addItem(coctail)
return success

alt success == true
    main --> coctail ++: onPickup(student1)
    coctail --> student ++: getInventory()
    return student1Inventory
    return 
    
else success == false
    note over inventory : can't test item usage
end

@enduml