@startuml StudentTeleportNoGasMaskComm
header Set up a student and move them to a gased room
hide footbox

participant M as "Main"
create R1 as "room1 : Room"
M --> R1 :  <<create>>
create R2 as "room2 : Room"
M --> R2 :  <<create>>
create S1 as "student1 : Student"
M --> S1 ++: <<create>>
create S1S as "student1State : StudentActions"
S1 --> S1S : <<create>>
create S1I as "student1Inventory : Inventory"
S1 --> S1I : <<create>>
create S1D as "student1Defense : DefaultDefense"
S1 --> S1D --: <<create>>

create gas as "gasEffect : GasEffect"
M --> gas : <<create>>

create gasMaskFinder as "bestGasMaskFinder : BestGasMaskFinder"
gas --> gasMaskFinder : <<create>>

M --> R2 ++ : addEffect(gasEffect)
return
M --> S1 ++ : teleport(room1, true)
return true
@enduml

