@startuml RoomTick
header Room tick
hide footbox

actor time as "TimePassing"
participant room as "room : Room"
participant effect as "roomEffect : RoomEffect"
participant actor as "actor : Actor"
participant door as "door : Door"

time -> room ++: tick()
loop for each door in room
    room -> door++ : tick()
    return
end
loop for each roomEffect
    room -> effect ++: tick()
    return active

    alt active == true
        loop for each actor 
            room -> effect ++: addEffect(actor)

            effect -> actor ++ : acceptEffect(effect, unless)
            ' ennek így kéne működnie, de nem így kódoltuk le ...
            
            return 
            return
        end
    else active == false
        room -> effect
        destroy effect
    end
end
return
 
participant unless as "unless : List<ItemFinder>"
@enduml