@startuml RoomTick
skinparam headerFontSize 20
skinparam HeaderFontColor #000000
skinparam HeaderFontStyle bold
header Room tick
hide footbox

actor time as "TimePassing"
participant room as "room : Room"
participant effect as "roomEffect : RoomEffect"
participant actor as "actor : Actor"
participant door as "door : Door"

time -> room ++: tick()
loop foreach door in room.doors
    room -> door++ : tick()
    return
end
loop foreach roomEffect in room.roomEffects
    room -> effect ++: tick()
    return active

    alt active == true
        loop foreach actor room.actors
            room -> effect ++: addEffect(actor)

            effect -> actor ++ : acceptEffect(effect, unless)
            ' ennek így kéne működnie, de nem így kódoltuk le ...
            
            return 
            return
        end
    else active == false
        room -> effect : <<destroy>>
        destroy effect
    end
end

room --> time
deactivate room

participant unless as "unless : List<ItemFinder>"
@enduml