@startuml WetEffectStudent
header Add wet effect to student
hide footbox

actor Controller as "Invoker"
participant Room as "room : Room"
participant Actor as "student : Student"
participant WetEffect as "wetEffect : WetEffect"

Controller -> Room ++: enter(student, false)
Room -> Room : isFull()

opt isFull == false

Room -> WetEffect ++: addEffect(professor)
WetEffect -> Actor++: acceptEffect(wetEffect, Null)
Actor -> WetEffect++: applyEffect(student)
return
return
return

end

return success

@enduml