@startuml WetEffectStudent
header Add wet effect to student
hide footbox

actor Controller as "Invoker"
participant Room as "room : Room"
participant List as "itemFinders : List<ItemFinder>"
participant Actor as "student : Student"
participant GasEffect as "wetEffect : WetEffect"

Controller -> Room : enter(student)
activate Room

Room -> Actor++: acceptEffect(wetEffect, itemFinders)
Actor -> GasEffect++: applyEffect(student)

return
return
return

@enduml