@startuml WetEffectProfessor
header Add wet effect to professor
hide footbox

actor Controller as "Invoker"
participant Room as "room : Room"
participant Actor as "professor : Professor"
participant State as "actionState : ActionState"
participant WetEffect as "wetEffect : WetEffect"

Controller -> Room ++: enter(professor, false)

Room -> Room : isFull()

opt isFull == false
    Room -> WetEffect ++: addEffect(professor)
    WetEffect -> Actor++: acceptEffect(wetEffect, Null)
    Actor -> WetEffect++: applyEffect(professor)

    create StunnedStep as "stunnedStep : StunnedStep"
    WetEffect --> StunnedStep: <<create>>
    WetEffect -> Actor++: setActionState(stunnedStep)
    Actor -> State ++ : setNextState(stunnedStep)
    return nextState
    return
    return
    return
    return
end

return success

@enduml