@startuml Pickup
skinparam headerFontSize 20
skinparam HeaderFontColor #000000
skinparam HeaderFontStyle bold
header Pick up
hide footbox

actor p as "Felhasználó"
participant btn as "useItem : JMenuItem"
p -> btn++ : kattintás

participant gm as "gameManager : GameManager"
btn -> gm++ : getCurrentPlayer()
return currentPlayer

participant player as "currentPlayer : Player"
participant item as "item : Item"
btn -> player++ : pickUp(item)

participant a as "actor : Actor"
player -> a++ : pickUp(item)


opt alive == true
    ' todo ez egy korábbi dokumentációból van
    ref over a
    Actor Pickup Item
    end ref

    ref over a
    Update Game Object
    end ref
end
    
return success

opt success == true
    player -> gm ++ : takeStep()
    return
end

return success

return 

@enduml