@startuml Use
skinparam headerFontSize 20
skinparam HeaderFontColor #000000
skinparam HeaderFontStyle bold
header Use
hide footbox

actor p as "Felhasználó"
participant btn as "useItem : JMenuItem"
p -> btn++ : kattintás

participant gm as "gameManager : GameManager"
btn -> gm++ : getCurrentPlayer()
return currentPlayer

participant player as "currentPlayer : Player"
participant item as "item : Item"
btn -> player++ : use(item)

participant a as "actor : Actor"
player -> a++ : use(item)

opt alive == true
    ' todo ez egy korábbi dokumentációból van
    ref over a
    Actor Use Item
    end ref

    ref over a
    Update Game Object
    end ref
    return 
end

player -> gm ++ : takeStep()
return

return 

return 
return

@enduml