@startuml StunnedPickUp
header Stunned Pick Up Item

hide footbox
autoactivate on

actor A as "Controller"
participant B as "actor : Actor"
participant D as "item : Item"
participant C as "state : StunnedStep"
A -> B : pickUp(item)
B -> C : pickUp(item)
return false
return false

@enduml