@startuml StunnedMove
header Stunned Move

hide footbox
autoactivate on

actor A as "Controller"
participant B as "actor : Actor"
participant D as "door : Door"
participant C as "state : StunnedStep"
A -> B : move(door)
B -> C : move(door)
return false
return false

@enduml