@startuml StunnedDropItem
header Stunned Drop Item

hide footbox
autoactivate on

actor A as "Controller"
participant B as "actor : Actor"
participant D as "item : Item"
participant C as "state : StunnedStep"
A -> B : drop(item)
B -> C : drop(item)
return
return

@enduml