@startuml DefenseStrategy
header Defense strategy
hide empty description

[*] --> DefaultDefense

DefaultDefense -> BeerDefense : setDefenseStrategy(beerDefense)
DefaultDefense -> DefaultDefense : tick()

state c <<choice>>

BeerDefense -> c : tick()
c --> BeerDefense : [usesLeft > 0]
c --> DefaultDefense : [usesLeft == 0]


@enduml