@startuml DefenseStrategy
header Defense strategy
hide empty description

[*] --> DefaultDefense

state c <<choice>>

BeerDefense --> c : tick()
c --> BeerDefense : [usesLeft > 0]
c --> DefaultDefense : [usesLeft == 0]

DefaultDefense --> DefaultDefense : tick()
DefaultDefense --> BeerDefense : setDefenseStrategy(beerDefense)


@enduml