@startuml DoorStates
header Door states
hide empty description

/'
Ha vita tárgyát képezné a condition - akkor UML 2.5.1-es 
standard specifikáció 371. oldalát tudom előszeretettel ajánlani
'/

[*] --> Visible

Visible --> Hidden : hide(duration)/remainingInvisibility = duration

state c <<choice>>

Hidden --> c : tick() / remainingInvisibility--

c --> Hidden : [remainingInvisibility > 0]
c --> Visible : [remainingInvisibility == 0]

@enduml