@startuml CoctailReviveState
header Cocktail revive state
hide empty description

[*] --> NotRevivedAnyone

' na itt nem tudom mi a függvény, mer ilyen nincs igazából
NotRevivedAnyone --> Revived : revive() == true
NotRevivedAnyone --> NotRevivedAnyone : revive() == false