@startuml CoctailReviveState
header Cocktail revive state
hide empty description

[*] --> NotRevivedAnyone

NotRevivedAnyone --> NotRevivedAnyone : revive() == false
NotRevivedAnyone --> Revived : revive() == true