@startuml DoorReappear
header Door reappear
hide footbox

actor time as "TimePassing"
participant room as "room : Room"
participant door as "door : Door"

time -> room ++: tick()
 
ref over room
    Room effect ticking
end ref
room -> door ++: tick()
return
return

@enduml