@startuml RoomMerge
header Room merge
hide footbox

' actor gm as "GameManager"
' participant r2 as "room2 : Room"
' participant r1 as "room1 : Room"

' gm -> r1 ++: merge(room2)
' return

' note over r1
'     a beolvadás a room1 belső működése
' end note


' látványosabb lenne, ha a room1 olvadna bele ilyenkor 
' a room2-be, mert akkor több függvényhívást használnánk
' így csak belső működés az egész

' lentebb itthagyom a látványosabb változatot, de
' lehet ez egy külön diagrammra kéne és innen csak megreferálni

actor gm as "GameManager"
participant r1 as "room1 : Room"
participant effect as "roomEffect : RoomEffect"
participant r1i as "room1inventory : Inventory"
participant r2 as "room2 : Room"
participant act as "actor : Actor"
participant d as "door : Door"

gm -> r1 ++ : merge(room2)

loop foreach effect in room1.roomEffects
    r1 -> r2 ++ : addEffect(roomEffect)
    return
end

r1 -> r1i ++: droppAll(room2)
    ref over r1i, r2
        DropAllTo
    end ref
return

loop foreach actor in room1.actors
    r1 -> act ++: teleport(room2, true)
    return
end

' door update is missing, it's too much work and not necessary (I guess)

@enduml