@startuml RoomSplit
skinparam headerFontSize 20
skinparam HeaderFontColor #000000
skinparam HeaderFontStyle bold
header Room Split
hide footbox

actor gm as "GameManager"
participant r1 as "room1 : Room"
participant ef1 as "roomEffect1 : RoomEffect"

gm -> r1 ++ : split()

create r2 as "room2 : Room"
r1 --> r2 ++: Room(capacity)
create r2i as "room2inventory : Inventory"
r2 --> r2i --: <<create>>

create d as "door : Door"
r1 --> d : Door(room1, room2)

' az ajtó hozzáadás ezek szerint belső működés

loop foreach effect in room1.roomEffects
    r1 -> ef1++: copy()
    create ef2 as "roomEffect2 : RoomEffect"
    ef1 --> ef2: <<create>>
    return roomEffect2
    r1 -> r2 ++ : addEffect(roomEffect2)
    return
end
return

@enduml