@startuml
header Actor Use Item

hide footbox
autoactivate on

actor A as "Controller"
participant C as "state : ActionState"
participant I as "inventory : Inventory"
participant B as "actor : Actor"
participant D as "item : Item"
participant R as "room : Room"

A -> B : useItem(item)
B -> C : useItem(item)
C -> D : use(actor)
ref over B, D, R : Use Item
opt usesLeft < 0
    D -> I : removeItem(item)
    destroy D
end
@enduml


