@startuml GasEffect
header Add gas effect to actor
hide footbox

participant Room as "room : Room"
participant Actor as "actor : Actor"
participant GasEffect as "gasEffect : GasEffect"

activate Room
create ItemFinder as "itemFinder : ItemFinder<GasMask>"
Room -> ItemFinder: <<create>>

create List as "itemFinders : List<ItemFinder>"
Room -> List: <<create>>

Room -> List++: add(itemFinder)
return
Room -> Actor++: acceptEffect(gasEffect, itemFinders)
Actor -> GasEffect++: applyEffect(actor)
GasEffect -> Actor++: dropAllTo(room)
ref over Actor, Room: DropAllTo
return

create StunnedStep as "stunnedStep : StunnedStep"
GasEffect -> StunnedStep: <<create>>
GasEffect -> Actor++: setActionState(stunnedStep)
return
return
return



@enduml