@startuml
header Apply Wet Effect to student
hide footbox
autoactivate on
actor room as "room : Room"
participant effect as "effect : WetEffect"
participant student as "student : Student"

room -> student : acceptEffect(effect)
student -> effect : applyEffect(student)
return
@enduml