@startuml AddRoomEffect
header Add room effect
hide footbox

Actor Actor as "Invoker"
participant Room as "room : Room"
create RoomEffect as "effect : RoomEffect"

Actor --> RoomEffect: <<create>>
Actor -> Room++: addEffect(roomEffect)
return


@enduml