@startuml AddRoomEffect
header Add room effect
hide footbox

Actor Actor as "Invoker"
participant Room as "room : Room"
create RoomEffect as "effect : RoomEffect"

Actor --> RoomEffect: <<create>>

participant A as "actor : Actor"

Actor -> Room++: addEffect(effect)
loop foreach actor in room.actors
    Room -> A ++: addEffect(effect)
    return    
end

return


@enduml