@startuml StickyEffect
skinparam headerFontSize 20
skinparam HeaderFontColor #000000
skinparam HeaderFontStyle bold
header Add sticky effect to room
hide footbox

participant Room as "room : Room"
participant Actor as "actor : Actor"
participant effect as "effect : StickyEffect"

-> Room
activate Room

Room -> effect ++: addEffect(actor)
effect -> Actor++: acceptEffect(effect, Null)
Actor -> effect ++: applyEffect(actor)

effect -> effect : checkLimit()

/'
Úgy működik, hogy van egy listánk, amibe ha az ember új, akkor letároljuk
és így meg tudjuk számolni hány új látogató jött a szobába
'/

return
return
return
return

@enduml