@startuml BeerDefense
header Beer Defense
hide footbox

participant student as "student : Student"
participant studentAction as "studentAction : StudentActions"
participant defense as "beerDefense : BeerDefense"
participant door as "door : Door"
participant room1 as "room1 : Room"
participant room2 as "room2 : Room"
participant professor as "professor : Professor"
participant action as "professorAction : ProfessorActions"
participant inventory as "studentInventory : Inventory"

ref over student, professor, inventory : Setup Beer Defense

-> student ++: move(door)
student -> studentAction ++: move(door)

studentAction -> student ++ : getLocation()
return room1

studentAction -> door ++: leadsTo(room1)
return room2

studentAction -> room2 ++: enter(student, false)
room2 -> room2 : isFull()

opt isFull == false
    room2 -> professor ++: attack()
    professor -> action ++: attack()
    action -> room2 ++: attack(professor)
    room2 -> student ++: attacked() 
    student -> defense ++: defend(studentInventory)

    ' a beer defense always returns true
    return true
    return 
    return
    return
    return

    room2 -> student ++: attack()
    student -> studentAction ++: attack()
    return
    return
end

return isSuccessful

opt isSuccessful
    studentAction -> room1 ++: leave(student)
    return
end

return
return

@enduml