@startuml DoorAppear
skinparam headerFontSize 20
skinparam HeaderFontColor #000000
skinparam HeaderFontStyle bold
header Door disappear
hide footbox

participant door as "door : Door"
participant student as "student : Student"
participant studentAction as "studentAction : StudentActions"
participant room1 as "room1 : Room"
participant room2 as "room2 : Room"

ref over door, room2 : Setup door disappear

-> student++: move(door)
student -> studentAction++ : move(door)
studentAction -> door ++: leadsTo(room1)
return room2
studentAction -> door ++: move(student, room2)
return false
return false
return false

@enduml