@startuml ProfessorGetsWet
header Professor gets wet
hide footbox

participant Professor as "professor : Professor"
participant ProfessorActions as "professorActions : ProfessorActions"
participant Door as "door : Door"
participant Room as "room1 : Room"
participant RoomEffect as "wetEffect : WetEffect"

ref over Professor, RoomEffect : Setup professor steps into wet room

-> Professor++ : move(door)
Professor -> ProfessorActions++ : move(door)
ProfessorActions -> Door++ : leadsTo(room1)
return room2

ProfessorActions -> Door ++: move(professor, room2)
Door -> Room ++: enter(professor, false)
Room -> Room : isFull()
opt isFull == true 
Room -> RoomEffect ++: addEffect(professor)
RoomEffect -> Professor ++: acceptEffect(wetEffect)
Professor -> RoomEffect ++: applyEffect(professor)

create StunnedStep as "stunnedStep : StunnedStep"
RoomEffect --> StunnedStep : <<create>>

RoomEffect -> Professor ++: setActionState(stunnedStep)
return
return 
return
return

Room -> Professor ++: attack()
Professor -> StunnedStep ++: attack()
return 
return

end

return success
return success
return success
return success
@enduml