@startuml ProfessorMoves
header Professor Moves
hide footbox

participant professor as "professor : Professor"
participant action as "professorAction : ProfessorActions"
participant door as "door : Door"
participant room1 as "room1 : Room"
participant room2 as "room2 : Room"
participant student as "student : Student"
participant defense as "studentDefense : DefaultDefense"
participant inventory as "studentInventory : Inventory"

--> professor ++: move(door)
professor --> action ++: move(door)

action --> door ++: leadsTo(room1)
return room2

action --> room2 ++: enter(professor)
return isSuccessful

opt isSuccessful
    action --> room1 ++: leave(professor)
    return

    action --> room2 ++: attack(professor)
    room2 --> student ++: attacked() 
    student --> defense ++: defend(studentInventory)

    ' ez garantáltan false lesz, mert üres az inventory-ja
    return false
    
    return 
    return
end

return
return

' itt lehet még fel kéne tüntetni a többi dolgot, amit a konstruktor hozott létre
' de annyira feleslegesnek érzem

@enduml