@startuml RoomMergeWithDifferentEffects
skinparam headerFontSize 10
skinparam HeaderFontColor #000000
skinparam HeaderFontStyle bold
header Two Rooms merge with one of them having Wet effect and the other with Gas effect.
hide footbox

participant R1 as "room1: Room"
participant R2 as "room2: Room"
participant D as "door : Door"

participant W as "wetEffect: WetEffect"

ref over R1, W : Setup Room1 merge with Room2

-> R1 ++: merge(room2)
R1 -> R2 ++: addEffect(wetEffect)
return

R1 --> D : <<destroy>>
destroy R1
destroy D

@enduml