@startuml FullRoom
header Rooms Merge with one Student and Item in each, enough room for both students
hide footbox

participant R1 as "room1 : Room"
participant R2 as "room2 : Room"
participant D as "door : Door"

participant S1 as "student1 : Student"
participant S1S as "student1State : StudentActions"

participant S2 as "student2 : Student"
participant S2S as "student2State : StudentActions"

participant B as "beer : Beer"

ref over R1, T : Setup Neighbouring Rooms, each with one Student and an Item
--> R1 ++: merge(room2)
R1 --> B ++: onDrop(room2)
B --> R2 ++: addItem(beer)
return
return
R1 --> R1 : removeItem(beer)
R1 --> S1 ++: teleport(room2, true)
S1 --> R2 ++: enter(student1)
R2 --> R2 : isFull()
opt isFull == false
    R2 --> S2 ++ : attack()
    S2 --> S2S ++ : attack()
    return
    return
    R2 --> S1 ++ : attack()
    S1 --> S1S ++ : attack()
    return
    return
end
return true
return
R1 --> D : <<destroy>>
destroy D
destroy R1

@enduml

