@startuml RoomSplitWithEffects
skinparam headerFontSize 40
skinparam HeaderFontColor #000000
skinparam HeaderFontStyle bold
header Setup a Room with a Student, who has a Camembert
hide footbox

participant S1 as "student : Student"
participant S1S as "studentState : StudentActions"
participant S1I as "studentInventory : Inventory"
participant R as "room : Room"
participant C as "camembert : Camembert"

ref over S1, C: Setup a Room with a Student, who has a Camembert
-> S1 ++: use(camembert)
S1 -> S1S ++: use(camembert)
S1S -> C ++: use(student)
create G as "gasEffect : GasEffect"
C -> G ++: <<create>>
create F as "bestGasMaskFinder : BestGasMaskFinder"
G -> F : <<create>>
deactivate G
C -> R ++: addEffect(gasEffect)
    R -> S1 ++ : acceptEffect(gasEffect, bestGasMaskFinder)
    S1 -> F ++: findIn(studentInventory)
    F -> S1I ++: acceptVisitor(bestGasMaskFinder)
    return
    return null
    S1 -> G ++ : applyEffect(student)
    G -> S1 ++: dropAllTo(room)
    S1 -> S1I ++ : dropAllTo(room)
    return
    return
    create S as "stunnedStep : StunnedStep"
    G --> S <<create>>

    G -> S1 ++: setActionState(stunnedStep)
    return
return 
return 
return

alt usesLeft > 0
    C --> S1S
else usesLeft <= 0
    C --> S1I++: removeItem(camembert)
    return camembert
    return
    destroy C
end

return
destroy S1S
return

@enduml

