@startuml RoomSplitWithEffects
header Student Tries to Move to Full Room
hide footbox

participant S1 as "student1 : Student"
participant S1S as "student1State : StudentActions"
participant D as "door : Door"
participant R1 as "room1 : Room"
participant R2 as "room2 : Room"
ref over S1, R2 : Setup Neighbouring Rooms, each with one Student
--> S1 ++: move(door)
S1 --> S1S ++: move(door)
S1S --> D ++: leadsTo(room1)
return room2
S1S --> R2 ++ : enter(student1)
R2 --> R2 : isFull()
opt isFull == true
    return false
    return false
    return false
end


@enduml

