@startuml StudentUsesCoctail
skinparam headerFontSize 40
skinparam HeaderFontColor #000000
skinparam HeaderFontStyle bold
header Student Uses Coctail
hide footbox

participant student as "student1 : Student"
participant actions as "student1Action : StudentActions"
participant inventory as "student1Inventory: Inventory"
participant coctail as "coctail : Coctail"
participant room as "room : Room"
participant student2 as "student2 : Student"
participant actions2 as "student2Action : StudentActions"

ref over student, actions2 : Setup Student Uses Coctail

-> student ++ : use(coctail)
student -> actions ++ : use(coctail)
actions -> coctail ++ : use(student)

coctail -> student ++ : getLocation()
return room

coctail -> room ++ : revive()
    room -> student2 ++ : revive()
    ' mivel az alive belső állapot, ezért le kell kérdezni a usertől, hogy él-e
    ' legalábbis ebben reménykedem, mert kill függvény nincs :(
    return success
return success

alt usesLeft > 0
    coctail --> actions
else usesLeft <= 0
    coctail -> inventory++: removeItem(coctail)
    return coctail
    return
    destroy coctail
end

return
return

@enduml