@startuml StudentDropsTransistor
header Student Drops Transistor
hide footbox

participant student as "student : Student"
participant actions as "studentAction : StudentActions"
participant inv as "studentInventory: Inventory"
participant room as "room : Room"
participant invR as "roomInventory: Inventory"
participant t1 as "transistor: Transistor"

ref over student, transistorB: Student Interacts with Transistor Setup

-> student ++ : drop(transistor)
student -> actions ++ : drop(transistor)

actions -> inv++: removeItem(transistor)
return transistor

actions -> room++: addItem(transistor)
    room -> t1 ++ : onDrop(room)
    ' transistor sets own loaction here
    return

    room -> invR++: addItem(transistor)
    return
return

return
return

@enduml