@startuml StudentMovesToRoomWithTVSZ
skinparam headerFontSize 40
skinparam HeaderFontColor #000000
skinparam HeaderFontStyle bold
header StudentMovesToRoomWithTVSZ
hide footbox

participant student as "student : Student"
participant studentAction as "studentAction : StudentActions"
participant door as "door : Door"
participant room1 as "room1 : Room"
participant room2 as "room2 : Room"
participant professor as "professor : Professor"
participant action as "professorAction : ProfessorActions"
participant inventory as "studentInventory : Inventory"
participant defense as "studentDefense : DefaultDefense"
participant tvsz as "tvsz: Tvsz"

ref over student, tvsz : Setup Student Moves To Room With TVSZ

-> student ++: move(door)
student -> studentAction ++: move(door)

studentAction -> door ++: leadsTo(room1)
return room2

studentAction -> door ++: move(student, room2)
door -> room2 ++: enter(student, false)

room2 -> room2 : isFull()

opt isFull == false

    room2 -> professor ++: attack()
    professor -> action ++: attack()
    action -> room2 ++: attack(professor)
    room2 -> student ++: attacked() 
    student -> defense ++: defend(studentInventory)

    create tvszfinder as "tvszFinder: BestTvszFinder"
    defense --> tvszfinder : <<create>>
    defense -> tvszfinder ++: findIn(studentInventory)
        tvszfinder -> inventory ++: acceptVisitor(tvszFinder)
            inventory -> tvsz ++: accept(tvszFinder)
            tvsz -> tvszfinder ++: visit(tvsz)
            return
            return
            return
            return tvsz

    defense -> tvsz ++: use(student)
    return

    return true
    return 
    return
    return
    return
    

    room2 -> student ++: attack()
    student -> studentAction ++: attack()
    return
    return
    
end

return isSuccessful
return isSuccessful

opt isSuccessful
    studentAction -> room1 ++: leave(student)
    return
end

return true
return true

@enduml