@startuml StudentMovesToEmptyRoom
skinparam headerFontSize 40
skinparam HeaderFontColor #000000
skinparam HeaderFontStyle bold
header Student Moves to another Room
hide footbox

participant S1 as "student1 : Student"
participant S1S as "student1State : StudentActions"
participant D as "door : Door"
participant R1 as "room1 : Room"
participant R2 as "room2 : Room"
participant S2 as "student2 : Student"
participant S2S as "student2State : StudentActions"
ref over S1, R2 : Setup Neighbouring Rooms, with a student in each of them
-> S1 ++: move(door)
S1 -> S1S ++: move(door)
S1S -> D ++: leadsTo(room1)
return room2

S1S -> D ++ : move(student1, room2)
D -> R2 ++ : enter(student1, false)
R2 -> R2 : isFull()
opt isFull == false
    R2 -> S1 ++ : attack()
    S1 -> S1S ++ : attack()
    return
    return

    R2 -> S2 ++ : attack()
    S2 -> S2S ++ : attack()
    return
    return
end
return success
return success

opt success == true
    S1S -> R1 ++ : leave(student1)
    return
end
return 
return 


@enduml

