@startuml UseSponge
header Use Sponge
hide footbox
participant Student as "student : Student"
participant Action as "studentAction : StudentAction"
participant Inventory as "studentInventory : Inventory"
participant Sponge as "sponge : Sponge"
participant Room as "room1 : Room"

ref over Student, Room : Setup use sponge

-> Student++ : use(sponge)
Student -> Action ++: use(sponge)
Action -> Sponge++ : use(student)

create RoomEffect as "wetEffect : WetEffect"
Sponge --> RoomEffect: <<create>>
Sponge -> Room++: addEffect(wetEffect)
Room -> Student++: acceptEffect(wetEffect, itemFinders)
Student -> RoomEffect++: applyEffect(student)

return
return
return
return
return
return

@enduml