@startuml BeerDefense
header Beer defense
hide footbox

' csak mi tudjuk, hogy ők azok, de ez generikus igazából 
actor prof as "Attacker"
participant student as "actor : Actor"
participant beerDefense as "beerDefense : BeerDefense"
participant inventory as "inventory : Inventory"

prof -> student ++ : attacked()
student -> beerDefense ++ : defend(inventory)
return true
return

@enduml