@startuml DefaultDefense
header Default defense
hide footbox

actor prof as "Attacker"
participant student as "actor : Actor"
participant item as "item : Tvsz"
participant defense as "defense : DefaultDefense"
participant inventory as "inventory : Inventory"

prof -> student : attacked()
activate student
student -> defense : defend(inventory)
activate defense

ref over defense, item, inventory
    Item finding
end ref 

alt item == null
    defense --> student : false
else item != null
    defense -> item ++: use(actor)
    return 
    return true
end

student --> prof
deactivate student
@enduml