@startuml Utilities
title Utilities

skinparam classAttributeIconSize 0
             
        JButton <|-- CustomButton
        class CustomButton{
            - action : Consumer<ActionEvent>
            - background : Color
            - highlightColor : Color
            - hasAnimation : boolean

            + setExpectedSize(size: Dimension): void
            - onClickAnimation(event: ActionEvent): void
            + setHighlight(highlight: boolean): void
            + setHasAnimation(hasAnimation: boolean): void
            + setBackground(color: Color): void
            + setHighlightColor(color: Color): void
        }

        DefaultButtomModel <|-- CustomButtonState
        class CustomButtonState {
            +isPressed(): boolean
            +isRollover(): boolean
            +setRollover(b: boolean): void
        }

        BasicScrollBarUI <|-- ScrollUI
        class ScrollUI {
            #createDecreaseButton(orientation: int): JButton
            #createIncreaseButton(orientation: int): JButton
            -createZeroButton(): JButton
        }

@enduml