@startuml AirFreshenerUse
skinparam headerFontSize 20
skinparam HeaderFontColor #000000
skinparam HeaderFontStyle bold
header Air freshener use
hide footbox

actor controller as "Controller"
participant student as "student : Student"
participant actionState as "studentActions : StudentActions"
participant af as "freshener : AirFreshener"
participant studentInventory as "studentInventory : Inventory"
participant room as "room : Room"
participant effect as "effect : RoomEffect"

controller -> student ++ : use(freshener)
student -> actionState ++ : use(freshener)
actionState -> af ++ : use(student)

af -> student ++ : getLocation()
return room

af -> room ++ : clean()

loop foreach effect in room.roomEffects
    room -> effect ++ : clean()
    effect -> room ++ : removeEffect(effect)
    return
    return success
end

return success

opt success == true
    ref over af, studentInventory : Delete Item
end

return
return
return

@enduml