@startuml BeerUse
skinparam headerFontSize 20
skinparam HeaderFontColor #000000
skinparam HeaderFontStyle bold
header Beer use
hide footbox

actor controller as "Controller"
participant student as "student : Student"
participant actionState as "studentActions : StudentActions"
participant beer as "beer : Beer"
participant studentInventory as "studentInventory : Inventory"
participant room as "room : Room"

controller -> student ++ : use(beer)
student -> actionState ++ : use(beer)
actionState -> beer ++ : use(student)

beer -> student ++ : getInventory()
return studentInventory
beer -> student ++ : getLocation()
return room
ref over student, beer, studentInventory, room : Actor Drop Item

create beerDefense as "beerDefense : BeerDefense"
beer --> beerDefense : <<create>>
beer -> student ++ : setDefenseStrategy(beerDefense)
return 

ref over beer, studentInventory : Delete Item
return 

return
return

@enduml