@startuml CamembertUse
header Camembert use

actor controller as "Controller"
participant actor as "actor : actor"
participant state as "actionState : ActionState"
participant camembert as "camembert : Camembert"
participant room as "room : Room"

controller -> actor++: use(camembert)
actor -> state ++: use(camembert)
state -> camembert++: use(actor)

camembert -> actor++: getLocation()
return room

ref over camembert, room : Apply effect
ref over camembert : DeleteItem

return
return

hide footbox
@enduml