@startuml CamembertUse
header Camembert use

actor controller as "Controller"
participant actor as "actor : actor"
participant state as "actionState : ActionState"
participant camembert as "camembert : Camembert"
participant room as "room : Room"

controller -> actor++: use(camembert)
actor -> state ++: use(camembert)
state -> camembert++: use(actor)

camembert -> actor++: getLocation()
return room

create gasEffect as "gasEffect : GasEffect"
camembert --> gasEffect : <<create>>
ref over camembert, room : Add room effect
ref over camembert : Delete Item

return
return
return

hide footbox
@enduml