@startuml DropAllTo
header DropAllTo
hide footbox
participant Actor as "actor : Actor"
participant Room as "room : Room"
participant Inventory as "inventory : Inventory"
participant Item as "item : Item"

-> Actor ++: dropAll(room)
Actor -> Inventory++: dropAll(room)
loop foreach Item
    Inventory -> Room++: addItem(item)
    Room -> Item ++: onDrop(room)
    return
    return true
    Inventory -> Inventory : removeItem(item)
end

return
return
@enduml