@startuml SpongeUse
header Sponge Use

actor controller as "Controller"
participant actor as "actor : actor"
participant state as "actionState : ActionState"
participant sponge as "sponge : Sponge"
participant room as "room : Room"
controller -> actor++: use(sponge)

actor -> state++: use(sponge)
state -> sponge++: use(actor)

sponge -> actor++: getLocation()
return room

create wetEffect as "wetEffect : WetEffect"
sponge --> wetEffect : <<create>>
ref over sponge, room : Add room effect
ref over sponge : Delete item

return
return
return

hide footbox
@enduml